<?php
/**
 * ReplicateParentAggregateEventRequestTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  HiCo\EventManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HighCohesion API
 *
 * HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)
 *
 * The version of the OpenAPI document: 1.0.15
 * Contact: admin@highcohesion.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HiCo\EventManagerClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReplicateParentAggregateEventRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ReplicateParentAggregateEventRequest
 * @package     HiCo\EventManagerClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReplicateParentAggregateEventRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReplicateParentAggregateEventRequest"
     */
    public function testReplicateParentAggregateEventRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "organisationId"
     */
    public function testPropertyOrganisationId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "jobId"
     */
    public function testPropertyJobId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "originalEventId"
     */
    public function testPropertyOriginalEventId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
