<?php
/**
 * UpdateEventEntityRequestTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  HiCo\EventManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HighCohesion API
 *
 * HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: admin@highcohesion.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HiCo\EventManagerClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateEventEntityRequestTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateEventEntityRequest
 * @package     HiCo\EventManagerClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateEventEntityRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateEventEntityRequest"
     */
    public function testUpdateEventEntityRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "destinationId"
     */
    public function testPropertyDestinationId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "destinationParentId"
     */
    public function testPropertyDestinationParentId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
