<?php
/**
 * JobApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  HiCo\EventManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HighCohesion API
 *
 * HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: admin@highcohesion.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace HiCo\EventManagerClient\Test\Api;

use \HiCo\EventManagerClient\Configuration;
use \HiCo\EventManagerClient\ApiException;
use \HiCo\EventManagerClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * JobApiTest Class Doc Comment
 *
 * @category Class
 * @package  HiCo\EventManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JobApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createJob
     *
     * Create a new job.
     *
     */
    public function testCreateJob()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createJobSchedule
     *
     * Create a job schedule.
     *
     */
    public function testCreateJobSchedule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSourceJob
     *
     * Trigger a job to be sent to the source.
     *
     */
    public function testCreateSourceJob()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteJob
     *
     * Delete jobs.
     *
     */
    public function testDeleteJob()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getJobById
     *
     * Get a job by job id.
     *
     */
    public function testGetJobById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getJobsBy
     *
     * Get a list of jobs by.
     *
     */
    public function testGetJobsBy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replicateJob
     *
     * Replicate job.
     *
     */
    public function testReplicateJob()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateJob
     *
     * Update job.
     *
     */
    public function testUpdateJob()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
